version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    entrypoint: ""
    command: ["sleep", "infinity"]
    network_mode: service:postgres

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
